spring:

  h2:
    console:
      enabled: true

  jpa:
    properties:
      hibernate:
        format_sql: true
    show_sql: true
    hibernate:
      ddl-auto: validate

security:
  jwt:
    token:
      secret-key: secret_key_hyeon9mak
      expire-length: 3600000 # 1Hour
